In [1]:
import numpy as np
import matplotlib.image as img
import matplotlib.pyplot as plt
from matplotlib import cm
import matplotlib.colors as colors

In [2]:
aa = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    
])

In [57]:
def compute_derivative_x_forward(I):
    
    D = np.zeros(I.shape)
    temp = np.zeros(I.shape)

    for i in range(len(I)-1):
        temp[i,:] = I[i+1,:]
    temp[-1,:] = I[-1,:]

    D = temp-I 
    return D

In [58]:
def compute_derivative_x_forward2(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    I1 = I[1:,:]
    I2 = np.vstack((I1,I[-1,:]))
    
    D = I2 - I
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [59]:
aa

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [60]:
res1 = compute_derivative_x_forward(aa)
res2 = compute_derivative_x_forward2(aa)


In [61]:
print(res1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


In [62]:
print(res2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]]


###################### backward x

In [63]:
def compute_derivative_x_backward(I):
    

    dd = np.zeros(I.shape)
    D = np.zeros(I.shape)

    for i in range(1,len(I)):
        dd[i,:] = I[i-1,:]
    dd[0,:] = I[0,:]
    
    D = I-dd 
    return D

In [64]:
def compute_derivative_x_backward2(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    I1 = I[0,:]
    I2 = np.vstack((I1,I[0:-1,:]))
    
    D = I - I2
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [65]:
res1 = compute_derivative_x_backward(aa)
res2 = compute_derivative_x_backward2(aa)


In [66]:
print(res1)
print(res2)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##################### x central

In [67]:
def compute_derivative_x_central(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    tmp = np.zeros([I.shape[0]+2,I.shape[1]])

    tmp[0] = I[0,:]
    tmp[-1] = I[-1,:]

    for i in range(len(I)):
        tmp[i+1] = I[i,:]
    
    for i in range(1,len(tmp)-1):
        D[i-1] = (tmp[i+1,:]-tmp[i-1,:])/2

    
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [68]:
def compute_derivative_x_central_(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    a1 = I[1:,:]
    a2 = np.vstack((a1,I[-1,:]))
    
    b1 = I[0,:]
    b2 = np.vstack((b1,I[0:-1,:]))
    
    D = (a2 - b2)/2
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [69]:
res1 = compute_derivative_x_central(aa)
res2 = compute_derivative_x_central_(aa)


In [70]:
print(res1)
print(res2)

[[0.5 0.5 0.5 0.5 0.5]
 [1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1. ]
 [0.5 0.5 0.5 0.5 0.5]]
[[0.5 0.5 0.5 0.5 0.5]
 [1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1. ]
 [0.5 0.5 0.5 0.5 0.5]]


############################### y forward

In [71]:
def compute_derivative_y_forward(I):
    D = np.zeros(I.shape)

    bb = np.zeros([I.shape[0],I.shape[1]+1])

    bb[:,-1] = I[:,-1]
    bb[:,0:-1] = I[:,:]

    partial1 = bb[:,0:-1]
    partial2 = bb[:,1:]

    D = partial2 - partial1
    
    return D

In [72]:
def compute_derivative_y_forward_(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    I1 = I[:,1:]
    I2 = np.hstack((I1,I[:,-1:]))
    
    D = I2 - I
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [73]:
res1 = compute_derivative_y_forward(aa)
res2 = compute_derivative_y_forward_(aa)

In [74]:
print(res1)
print(res2)

[[1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 0.]]
[[1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 1 1 0]]


############################# Y Backward

In [75]:
def compute_derivative_y_backward(I):
    D = np.zeros(I.shape)

    bb = np.zeros([I.shape[0],I.shape[1]+1])
    bb[:,0] = I[:,0]
    bb[:,1:]=I 

    partial1 = bb[:,:-1]
    partial2 = bb[:,1:]

    D = partial2 - partial1

    

   
    return D

In [76]:
def compute_derivative_y_backward_(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #

    I1 = I[:,0:1]
    I2 = np.hstack((I1,I[:,0:-1]))
    
    D = I - I2
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [77]:
res1 = compute_derivative_y_backward(aa)
res2 = compute_derivative_y_backward_(aa)


In [78]:
print(res1)
print(res2)

[[0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]]
[[0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 1 1]]


In [79]:
def compute_derivative_y_central(I):
    
    bb = np.zeros([I.shape[0],I.shape[1]+2])
    bb[:,1:-1]=I
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    bb[:,0]=bb[:,1]
    bb[:,-1]=bb[:,-2]    
    
    D = [] 
    for i in range(len(bb)):
        tmp = []
        for j in range(len(bb[i])-2):
            tmp.append((bb[i][j+2]-bb[i][j])/2)
        D.append(tmp)
    D = np.array(D)    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [80]:
def compute_derivative_y_central_(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    a1 = I[:,1:]
    a2 = np.hstack((a1,I[:,-1:]))
    
    b1 = I[:,0:1]
    b2 = np.hstack((b1,I[:,0:-1]))

    D = (a2 - b2)/2
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [81]:
aa

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [82]:
res1 = compute_derivative_y_central(aa)
res2 = compute_derivative_y_central_(aa)

In [83]:
print(res1)
print()
print(res2)

[[0.5 1.  1.  1.  0.5]
 [0.5 1.  1.  1.  0.5]
 [0.5 1.  1.  1.  0.5]
 [0.5 1.  1.  1.  0.5]]

[[0.5 1.  1.  1.  0.5]
 [0.5 1.  1.  1.  0.5]
 [0.5 1.  1.  1.  0.5]
 [0.5 1.  1.  1.  0.5]]


In [84]:
def compute_norm_gradient_central(I):
    
    norm_gradient = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    norm1 = compute_derivative_x_central(I)
    norm2 = compute_derivative_y_central(I)


    norm_gradient = np.square(norm1)+np.square(norm2)
    #norm_gradient = np.sqrt(norm_gradient)
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return norm_gradient

In [85]:
def compute_norm_gradient_central_(I):
    
    norm_gradient = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    a1 = I[1:,:]
    a2 = np.vstack((a1,I[-1,:]))
    
    b1 = I[0,:]
    b2 = np.vstack((b1,I[0:-1,:]))
    
    c = (a2 - b2)/2
    
    d1 = I[:,1:]
    d2 = np.hstack((d1,I[:,-1:]))
    
    e1 = I[:,0:1]
    e2 = np.hstack((e1,I[:,0:-1]))

    f = (d2 - e2)/2
    
    norm_gradient = c*c + f*f
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return norm_gradient

In [86]:
res1 = compute_norm_gradient_central(aa)
res2 = compute_norm_gradient_central_(aa)

In [87]:
print(res1)
print(res2)

[[0.5  1.25 1.25 1.25 0.5 ]
 [1.25 2.   2.   2.   1.25]
 [1.25 2.   2.   2.   1.25]
 [0.5  1.25 1.25 1.25 0.5 ]]
[[0.5  1.25 1.25 1.25 0.5 ]
 [1.25 2.   2.   2.   1.25]
 [1.25 2.   2.   2.   1.25]
 [0.5  1.25 1.25 1.25 0.5 ]]
