In [1]:
import numpy as np 
import pandas as pd 

In [24]:
aa = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    
])

In [27]:
for i in range(len(aa)):
    for j in range(len(aa[i])):
        print(aa[i][j],end=' ')
    print()

1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 


In [29]:
bb = np.zeros(aa.shape)
print(bb)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
for i in range(1,len(aa)):
    bb[i-1] = aa[i,:] 

In [34]:
print(bb)

[[2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]
 [1. 1. 1. 1. 1.]]


In [54]:
def compute_derivative_x_forward(I):

    dd = np.zeros(I.shape)
    D = np.zeros(I.shape)

    for i in range(1,len(I)):
        dd[i,:] = I[i-1,:]
    dd[0,:] = I[0,:]
    print(dd)
    D = I-dd 
    return D

In [56]:
res = compute_derivative_x_forward(aa)
print(res)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [57]:
aa = np.array([
    [1,1,1,1,1],
    [2,2,2,2,2],
    [3,3,3,3,3],
    [4,4,4,4,4]
])

In [59]:
bb = np.zeros(aa.shape)
cc = np.zeros(aa.shape)

In [67]:
for i in range(len(aa)-1):
    cc[i,:] = aa[i+1,:]

cc[-1,:] = aa[-1,:]

In [68]:
print(cc)

[[2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


In [69]:
bb = aa - cc
print(bb)

[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]]


In [70]:
def compute_derivative_x_backward(I):
    D = np.zeros(I.shape)
    temp = np.zeros(I.shape)

    for i in range(len(I)-1):
        temp[i,:] = I[i+1,:]
    temp[-1,:] = I[-1,:]

    D = I-temp 
    return D

In [71]:
res = compute_derivative_x_backward(aa)
print(res)

[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]]


In [78]:
aa = np.array([

    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8]
])

In [79]:
print(aa)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [83]:
bb = np.zeros(aa.shape)

In [92]:
cc = np.zeros([aa.shape[0]+2,aa.shape[1]])
cc[0] = aa[0,:]
for i in range(len(aa)):
    cc[i+1] = aa[i,:]
cc[-1] = aa[-1,:]
print(cc)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]
 [4. 5. 6. 7. 8.]]


In [99]:
dd = np.zeros(aa.shape)

In [100]:
for i in range(1,len(cc)-1):
    dd[i-1] = cc[i+1,:]-cc[i-1,:]


In [101]:
dd

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.]])

In [102]:
def compute_derivative_x_central(I):

    D = np.zeros(I.shape)

    tmp = np.zeros([I.shape[0]+2,I.shape[1]])
    tmp[0] = I[0,:]
    tmp[-1] = I[-1,:]

    for i in range(len(I)):
        tmp[i+1] = I[i,:]
    
    for i in range(1,len(tmp)-1):
        D[i-1] = tmp[i+1,:]-tmp[i-1,:]
    return D

In [103]:
res = compute_derivative_x_central(aa)
print(res)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]]


In [104]:
aa = np.array([
    [0,1,0,1,0,1],
    [0,1,0,1,0,1],
    [0,1,0,1,0,1],
    [0,1,0,1,0,1]
])

In [105]:
aa.T

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1]])

In [108]:
tt = np.array([
    [1,1,1,1,1],
    [0,0,0,0,0],
    [1,1,1,1,1],
    [0,0,0,0,0]
])

In [109]:
res = compute_derivative_x_backward(tt)
print(res)

[[ 1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.]]


In [116]:
ss = compute_derivative_x_forward(tt)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [115]:
print(ss)

[[ 0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.]]


In [117]:
res1 = compute_derivative_x_central(tt)
print(res1)

[[-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1.]]


In [145]:
aa = np.array([
    [1,3,1,3,1],
    [3,1,3,1,3],
    [1,3,1,3,1],
    [3,1,3,1,3]
])

In [170]:
bb = np.zeros(aa.shape)

In [172]:
cc = np.zeros([aa.shape[0],aa.shape[1]+1])
cc[:,-1]=aa[:,-1]

for i in range(len(aa)):
    for j in range(len(aa[0])):
        cc[i][j] = aa[i][j]
print(cc)

[[1. 3. 1. 3. 1. 1.]
 [3. 1. 3. 1. 3. 3.]
 [1. 3. 1. 3. 1. 1.]
 [3. 1. 3. 1. 3. 3.]]


In [173]:
cc.T

array([[1., 3., 1., 3.],
       [3., 1., 3., 1.],
       [1., 3., 1., 3.],
       [3., 1., 3., 1.],
       [1., 3., 1., 3.],
       [1., 3., 1., 3.]])

In [176]:
res = compute_derivative_x_forward(cc.T)
print(res.T)

[[1. 3. 1. 3.]
 [1. 3. 1. 3.]
 [3. 1. 3. 1.]
 [1. 3. 1. 3.]
 [3. 1. 3. 1.]
 [1. 3. 1. 3.]]
[[ 0.  2. -2.  2. -2.  0.]
 [ 0. -2.  2. -2.  2.  0.]
 [ 0.  2. -2.  2. -2.  0.]
 [ 0. -2.  2. -2.  2.  0.]]


In [183]:
example = [
	[0,0,0,0,0],
	[0,0,1,0,3],
	[0,2,5,0,1],
	[4,2,4,4,2],
	[3,5,1,3,1]
]

In [184]:
cols = []
for row in example:
    cols.append(row[0])

In [186]:
cols =[row[0] for row in example]
print(cols)

[0, 0, 0, 4, 3]


In [187]:
cols  = list(zip(*example))

In [188]:
print(cols)

[(0, 0, 0, 4, 3), (0, 0, 2, 2, 5), (0, 1, 5, 4, 1), (0, 0, 0, 4, 3), (0, 3, 1, 2, 1)]
