In [3]:
import numpy as np 
import pandas as pd 

In [4]:
aa = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    
])

In [9]:
def compute_derivative_x_forward(I):

    dd = np.zeros(I.shape)
    D = np.zeros(I.shape)

    for i in range(1,len(I)):
        dd[i,:] = I[i-1,:]
    dd[0,:] = I[0,:]
    
    D = I-dd 
    return D

In [10]:
res = compute_derivative_x_forward(aa)
print(res)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
def compute_derivative_x_backward(I):
    D = np.zeros(I.shape)
    temp = np.zeros(I.shape)

    for i in range(len(I)-1):
        temp[i,:] = I[i+1,:]
    temp[-1,:] = I[-1,:]

    D = I-temp 
    return D

In [17]:
res = compute_derivative_x_backward(aa)
print(res)

[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]]


In [25]:
def compute_derivative_x_central(I):

    D = np.zeros(I.shape)

    tmp = np.zeros([I.shape[0]+2,I.shape[1]])
    tmp[0] = I[0,:]
    tmp[-1] = I[-1,:]

    for i in range(len(I)):
        tmp[i+1] = I[i,:]
    
    for i in range(1,len(tmp)-1):
        D[i-1] = tmp[i+1,:]-tmp[i-1,:]
    return D

In [26]:
res = compute_derivative_x_central(aa)
print(res)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]]


In [81]:
def compute_derivative_y_forward(I):
    D = np.zeros(I.shape)
    bb = np.zeros([I.shape[0],I.shape[1]+1])
    bb[:,-1]=I[:,-1]
    bb[:,0:-1] = I[:,:]

    cc = bb[:,0:-1]
    dd = bb[:,1:]

    D = dd-cc
    return D

In [82]:
res = compute_derivative_y_forward(aa)
print(res)

[[ 2. -2.  2. -2.  0.]
 [-2.  2. -2.  2.  0.]
 [ 2. -2.  2. -2.  0.]
 [-2.  2. -2.  2.  0.]]


In [83]:
def compute_derivative_y_backward(I):
    D = np.zeros(I.shape)
    
    bb = np.zeros([I.shape[0],I.shape[1]+1])
    bb[:,0] = I[:,0]
    bb[:,1:]=I 
    
    test1 = bb[:,:-1]
    test2 = bb[:,1:]
    D = test2-test1
    return D


In [85]:
res1 = compute_derivative_y_backward(aa)
print(res1)

[[ 0.  2. -2.  2. -2.]
 [ 0. -2.  2. -2.  2.]
 [ 0.  2. -2.  2. -2.]
 [ 0. -2.  2. -2.  2.]]


In [86]:
def compute_derivative_y_central(I):
    bb = np.zeros([I.shape[0],I.shape[1]+2])
    bb[:,1:-1] = I 
    bb[:,0] = bb[:,1]
    bb[:,-1]=bb[:,-2]

    D = [] 
    for i in range(len(bb)):
        tmp =[] 
        for j in range(len(bb[i])-2):
            tmp.append(bb[i][j+2]-bb[i][j])
        D.append(tmp)
    
    D = np.array(D)
    return D

In [87]:
res2 = compute_derivative_y_central(aa)
print(res2)

[[ 2.  0.  0.  0. -2.]
 [-2.  0.  0.  0.  2.]
 [ 2.  0.  0.  0. -2.]
 [-2.  0.  0.  0.  2.]]


In [88]:
def compute_norm_gradient_central(aa):
    
    norm_gradient = np.zeros(aa.shape)

    norm1 = compute_derivative_x_central(aa)
    norm2 = compute_derivative_y_central(aa)


    norm_gradient = np.square(norm1)+np.square(norm2)

    return norm_gradient

In [89]:
res4 = compute_norm_gradient_central(aa)
res4

array([[8., 4., 4., 4., 8.],
       [4., 0., 0., 0., 4.],
       [4., 0., 0., 0., 4.],
       [8., 4., 4., 4., 8.]])