In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],
             [4,5,6]])

b = np.array([[3,2],
             [4,4],
             [5,5]])

In [5]:
c = a.dot(b)

In [6]:
print(c)

[[26 25]
 [62 58]]


In [9]:
import numpy as np

# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
A                   = np.array([[4.1,5.3],
                               [-3.9,8.4],
                               [6.4,-1.8]])
size_A              = A.shape

print(A)


[[ 4.1  5.3]
 [-3.9  8.4]
 [ 6.4 -1.8]]


In [8]:
AT = A.transpose()
print(AT)

[[ 4.1 -3.9  6.4]
 [ 5.3  8.4 -1.8]]


In [10]:
c = A.dot(AT)
print(c)

[[ 44.9   28.53  16.7 ]
 [ 28.53  85.77 -40.08]
 [ 16.7  -40.08  44.2 ]]


In [20]:
A = np.array([[1.,2.],
             [3.,4.]])

AT = A.transpose()
print(A)
print(AT)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]


In [21]:
ATA = AT.dot(A)
print(ATA)

[[10. 14.]
 [14. 20.]]


In [22]:
print(A)

[[1. 2.]
 [3. 4.]]


In [23]:
#np.linalg.inv()
B = np.linalg.inv(A)
print(B)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [25]:
C = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(C)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
import numpy as np


np.random.seed(0)
# ++++++++++++++++++++++++++++++++++++++++++++++++++
# YOUR CODE HERE
A                   = np.array([[2.7,3.5],
                               [3.2,-8.2]])
size_A              = A.shape

AT                  = A.transpose()
size_AT             = AT.shape

mul_AT_A            = AT.dot(A)
size_mul_AT_A       = mul_AT_A.shape

invA                = np.linalg.inv(A)
size_invA           = invA.shape

inv_mul_AT_A        = np.linalg.inv(mul_AT_A)
size_inv_mul_AT_A   = inv_mul_AT_A.shape
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('******************************')
print('A = ')
print(A)
print('******************************')
print('size of A = ')
print(size_A)

print('******************************')
print('AT = transpose of A ')
print(AT)
print('******************************')
print('size of AT = ')
print(size_AT)

print('******************************')
print('AT A = multiplication of AT and A')
print(mul_AT_A)
print('******************************')
print('size of multiplication of AT and A = ')
print(size_mul_AT_A)

print('******************************')
print('inverse of A = ')
print(invA)
print('******************************')
print('size of inverse of A = ')
print(size_invA)

print('******************************')
print('inverse of multiplication of A transpose and A = ')
print(inv_mul_AT_A)
print('******************************')
print('size of inverse of multiplication of A transpose and A = ')
print(size_inv_mul_AT_A)
print('******************************')

******************************
A = 
[[ 2.7  3.5]
 [ 3.2 -8.2]]
******************************
size of A = 
(2, 2)
******************************
AT = transpose of A 
[[ 2.7  3.2]
 [ 3.5 -8.2]]
******************************
size of AT = 
(2, 2)
******************************
AT A = multiplication of AT and A
[[ 17.53 -16.79]
 [-16.79  79.49]]
******************************
size of multiplication of AT and A = 
(2, 2)
******************************
inverse of A = 
[[ 0.24595081  0.104979  ]
 [ 0.0959808  -0.0809838 ]]
******************************
size of inverse of A = 
(2, 2)
******************************
inverse of multiplication of A transpose and A = 
[[0.07151239 0.01510496]
 [0.01510496 0.01577069]]
******************************
size of inverse of multiplication of A transpose and A = 
(2, 2)
******************************


In [64]:
np.random.seed(0)

A = np.random.randint(1,5,size=(3,3))
invA = np.linalg.inv(A)

In [65]:
print(A)

[[1 4 2]
 [1 4 4]
 [4 4 2]]


In [66]:
print(invA)

[[-0.33333333  0.          0.33333333]
 [ 0.58333333 -0.25       -0.08333333]
 [-0.5         0.5        -0.        ]]


In [67]:
print(A.dot(invA))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
